### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jackhump** [plagnollab/RNASeq_pipeline#12]
I've been trying to run this dataset through the RNAseq pipeline. Here are my conditions from the support file:
export RNASEQPIPBASE=$RNASEQPIPBASE
export RNASEQBUNDLE=$RNASEQBUNDLE
pipeline=${RNASEQPIPBASE}/RNAseq_pipeline_v8.sh
###### 

species=human_hg38
submit=yes
force=yes

QC=yes
starStep1a=yes
starStep1b=yes
starStep2=yes

summary=yes
prepareCounts=yes
Rdeseq=yes
Rdexseq=yes

oFolder=/cluster/scratch3/vyp-scratch2/Humphrey_datasets/TDP_ENCODE/dataset_2/processed
iFolder=/cluster/scratch3/vyp-scratch2/Humphrey_datasets/TDP_ENCODE/dataset_2/

dataframe=${iFolder}/encode_tdp_2_support.tab
code=encode_dataset1

sh $pipeline --QC ${QC} --iFolder ${iFolder} --oFolder ${oFolder} --dataframe ${dataframe} --code ${code} --prepareCounts ${prepareCounts} --Rdexseq ${Rdexseq} --Rdeseq ${Rdeseq}  --summary ${summary} --starStep1a ${starStep1a} --starStep1b ${starStep1b} --starStep2 ${starStep2} --species ${species} --submit ${submit} --force ${force}

At first it was stopping because of typos (file_exists vs files_exist) and then it was stopping because of unbounded variables (finalOfolder, does it have to be defined at every function again Niko? I've now declared it within every function and that error disappeared) and then finally the $paired variable is unbound.
I got to the point where Step1a and Step1b submit but then due to wanting to go home on a Friday I used git checkout to roll my local version of the pipeline back to an older version (d1932e57bfb025be605fe6e157d2b0f2a7f5e0e2) and ran it. All the steps submitted. I guess we'll fix this on Monday.

**Comment by vplagnol** [comment]
So all they say is true? It is actually possible to checkout an old version
of a git repo?

On Fri, Dec 4, 2015 at 6:03 PM, Jack Humphrey notifications@github.com
wrote:

> I've been trying to run this dataset through the RNAseq pipeline. Here are
> my conditions from the support file:
> export RNASEQPIPBASE=$RNASEQPIPBASE
> export RNASEQBUNDLE=$RNASEQBUNDLE
> pipeline=${RNASEQPIPBASE}/RNAseq_pipeline_v8.sh
> 
> #############
> species=human_hg38
> submit=yes
> force=yes
> 
> QC=yes
> starStep1a=yes
> starStep1b=yes
> starStep2=yes
> 
> summary=yes
> prepareCounts=yes
> Rdeseq=yes
> Rdexseq=yes
> 
> oFolder=/cluster/scratch3/vyp-scratch2/Humphrey_datasets/TDP_ENCODE/dataset_2/processed
> 
> iFolder=/cluster/scratch3/vyp-scratch2/Humphrey_datasets/TDP_ENCODE/dataset_2/
> 
> dataframe=${iFolder}/encode_tdp_2_support.tab
> code=encode_dataset1
> 
> sh $pipeline --QC ${QC} --iFolder ${iFolder} --oFolder ${oFolder}
> --dataframe ${dataframe} --code ${code} --prepareCounts ${prepareCounts}
> --Rdexseq ${Rdexseq} --Rdeseq ${Rdeseq} --summary ${summary} --starStep1a
> ${starStep1a} --starStep1b ${starStep1b} --starStep2 ${starStep2} --species
> ${species} --submit ${submit} --force ${force}
> 
> At first it was stopping because of typos (file_exists vs files_exist) and
> then it was stopping because of unbounded variables (finalOfolder, does it
> have to be defined at every function again Niko? I've now declared it
> within every function and that error disappeared) and then finally the
> $paired variable is unbound.
> I got to the point where Step1a and Step1b submit but then due to wanting
> to go home on a Friday I used git checkout to roll my local version of the
> pipeline back to an older version (d1932e5
> https://github.com/plagnollab/RNASeq_pipeline/commit/d1932e57bfb025be605fe6e157d2b0f2a7f5e0e2)
> and ran it. All the steps submitted. I guess we'll fix this on Monday.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/plagnollab/RNASeq_pipeline/issues/12.

## 

Vincent Plagnol
University College London Genetics Institute
Darwin building, office 210
Gower Street, London, WC1E 6BT
Cell: +44-(0)7946-546923
Office: +44-(0) 2031-084002
Website: http://www.ucl.ac.uk/ugi/research/vincentplagnol
Lab blog: http://plagnol-lab.blogspot.co.uk/

**Comment by pontikos** [comment]
What exactly are you running can you send the path to your script. Will fix
tomorrow.

**Comment by pontikos** [comment]
And no there is no scoping in bash all variables are global.

**Comment by jackhump** [comment]
Yes Vincent it's true, Chris showed me. It was glorious. I managed to leave work on time.

I just typed:

$ git checkout <commit number>

and it reset my version to Monday's edition of the pipeline.

regards,

Jack

Jack Humphrey | PhD student

Institute of Neurology & UCL Genetics Institute | University College London

M: 07896 208 263

**Comment by vplagnol** [comment]
So the updated script is running now for step2, just pushed some fix to the
repo.

On Fri, Dec 4, 2015 at 7:01 PM, Nikolas Pontikos notifications@github.com
wrote:

> What exactly are you running can you send the path to your script. Will fix
> tomorrow.
> 
> On Friday, 4 December 2015, Vincent Plagnol notifications@github.com
> wrote:
> 
> > So all they say is true? It is actually possible to checkout an old
> > version
> > of a git repo?
> > 
> > On Fri, Dec 4, 2015 at 6:03 PM, Jack Humphrey <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > 
> > wrote:
> > 
> > > I've been trying to run this dataset through the RNAseq pipeline. Here
> > > are
> > > my conditions from the support file:
> > > export RNASEQPIPBASE=$RNASEQPIPBASE
> > > export RNASEQBUNDLE=$RNASEQBUNDLE
> > > pipeline=${RNASEQPIPBASE}/RNAseq_pipeline_v8.sh
> > > 
> > > #############
> > > species=human_hg38
> > > submit=yes
> > > force=yes
> > > 
> > > QC=yes
> > > starStep1a=yes
> > > starStep1b=yes
> > > starStep2=yes
> > > 
> > > summary=yes
> > > prepareCounts=yes
> > > Rdeseq=yes
> > > Rdexseq=yes
> > 
> > oFolder=/cluster/scratch3/vyp-scratch2/Humphrey_datasets/TDP_ENCODE/dataset_2/processed
> > 
> > 
> > iFolder=/cluster/scratch3/vyp-scratch2/Humphrey_datasets/TDP_ENCODE/dataset_2/
> > 
> > > dataframe=${iFolder}/encode_tdp_2_support.tab
> > > code=encode_dataset1
> > > 
> > > sh $pipeline --QC ${QC} --iFolder ${iFolder} --oFolder ${oFolder}
> > > --dataframe ${dataframe} --code ${code} --prepareCounts
> > > ${prepareCounts}
> > > --Rdexseq ${Rdexseq} --Rdeseq ${Rdeseq} --summary ${summary}
> > > --starStep1a
> > > ${starStep1a} --starStep1b ${starStep1b} --starStep2 ${starStep2}
> > > --species
> > > ${species} --submit ${submit} --force ${force}
> > > 
> > > At first it was stopping because of typos (file_exists vs files_exist)
> > > and
> > > then it was stopping because of unbounded variables (finalOfolder, does
> > > it
> > > have to be defined at every function again Niko? I've now declared it
> > > within every function and that error disappeared) and then finally the
> > > $paired variable is unbound.
> > > I got to the point where Step1a and Step1b submit but then due to
> > > wanting
> > > to go home on a Friday I used git checkout to roll my local version of
> > > the
> > > pipeline back to an older version (d1932e5
> > > <
> > 
> > https://github.com/plagnollab/RNASeq_pipeline/commit/d1932e57bfb025be605fe6e157d2b0f2a7f5e0e2
> > 
> > > )
> > > and ran it. All the steps submitted. I guess we'll fix this on Monday.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/plagnollab/RNASeq_pipeline/issues/12.
> > 
> > ## 
> > 
> > Vincent Plagnol
> > University College London Genetics Institute
> > Darwin building, office 210
> > Gower Street, London, WC1E 6BT
> > Cell: +44-(0)7946-546923
> > Office: +44-(0) 2031-084002
> > Website: http://www.ucl.ac.uk/ugi/research/vincentplagnol
> > Lab blog: http://plagnol-lab.blogspot.co.uk/
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/plagnollab/RNASeq_pipeline/issues/12#issuecomment-162052317
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/plagnollab/RNASeq_pipeline/issues/12#issuecomment-162053136
> .

## 

Vincent Plagnol
University College London Genetics Institute
Darwin building, office 210
Gower Street, London, WC1E 6BT
Cell: +44-(0)7946-546923
Office: +44-(0) 2031-084002
Website: http://www.ucl.ac.uk/ugi/research/vincentplagnol

**Comment by pontikos** [comment]
ok great thanks a lot Vincent and sorry again guys!
Is it all good then? can we close this issue?
