### ISSUE TITLE
RNASeq Pipeline path errors

### ISSUE THREAD

**Issue by skgtjt1** [plagnollab/RNASeq_pipeline#13]
Hi hope you can help, the RNAseq pipeline has stopped working, I think due to the scratch3 drive being moved/removed. Here's the error:

> File /cluster/scratch3/vyp-scratch2/reference_datasets/RNASeq/Mouse/Mus_musculus.GRCm38.82_fixed.gtf does not exist

Were the bundles moved elsewhere? Or am I just having access issues do you think?

Many thanks

**Comment by jackhump** [comment]
I've now moved most of the currently used species bundles to a new drive.
