### ISSUE TITLE
read.HTSeqCounts

### ISSUE THREAD

**Issue by kittyl** [plagnollab/RNASeq_pipeline#3]
The latest version of DEXSeq no longer has this function. 
It has been replaced with DEXSeqDataSetFromHTSeq
Will need to fix.

**Comment by vplagnol** [comment]
Yes, I think I replaced that in the dexseq pipeline.
But perhaps not the deseq steps. I was thinking of reading the deseq
vignette to see how they suggest to do it.

On Thu, Feb 5, 2015 at 10:09 AM, kittyl notifications@github.com wrote:

> The latest version of DEXSeq no longer has this function.
> It has been replaced with DEXSeqDataSetFromHTSeq
> Will need to fix.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/plagnollab/RNASeq_pipeline/issues/3.

## 

Vincent Plagnol
University College London Genetics Institute
Darwin building, office 210
Gower Street, London, WC1E 6BT
Cell: +44-(0)7946-546923
Office: +44-(0) 2031-084002
Website: http://www.ucl.ac.uk/ugi/research/vincentplagnol
Lab blog: http://plagnol-lab.blogspot.co.uk/

**Comment by kittyl** [comment]
Ok. I think it would still be good if we can keep the counts_prepare part separate from the deseq and dexseq analysis.

**Comment by vplagnol** [comment]
Yes I think it is a good idea, just needs a bit of tweaking.

On Thu, Feb 5, 2015 at 10:46 AM, kittyl notifications@github.com wrote:

> Ok. I think it would still be good if we can keep the counts_prepare part
> separate from the deseq and dexseq analysis.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/plagnollab/RNASeq_pipeline/issues/3#issuecomment-73027269
> .

## 

Vincent Plagnol
University College London Genetics Institute
Darwin building, office 210
Gower Street, London, WC1E 6BT
Cell: +44-(0)7946-546923
Office: +44-(0) 2031-084002
Website: http://www.ucl.ac.uk/ugi/research/vincentplagnol
