### ISSUE TITLE
Modify pipeline to use deseq2

### ISSUE THREAD

**Issue by kittyl** [plagnollab/RNASeq_pipeline#4]
I am going to add an R script to use deseq2 instead of deseq

**Comment by vplagnol** [comment]
Go for it!

On Thu, Feb 5, 2015 at 11:07 AM, kittyl notifications@github.com wrote:

> I am going to add an R script to use deseq2 instead of deseq
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/plagnollab/RNASeq_pipeline/issues/4.

## 

Vincent Plagnol
University College London Genetics Institute
Darwin building, office 210
Gower Street, London, WC1E 6BT
Cell: +44-(0)7946-546923
Office: +44-(0) 2031-084002
Website: http://www.ucl.ac.uk/ugi/research/vincentplagnol
Lab blog: http://plagnol-lab.blogspot.co.uk/
