### ISSUE TITLE
cannot find bundle/human_hg38/biomart/biomart_annotations_human.tab

### ISSUE THREAD

**Issue by pontikos** [plagnollab/RNASeq_pipeline#7]
Is this file not meant to be stored in the repo?

```
> annotations <- read.table(annotation.file, header = TRUE, sep = '\t', quote = "")
Error in file(file, "rt") : cannot open the connection
Calls: read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/home/rmhanpo/bin/RNASeq_pipeline/bundle/human_hg38/biomart/biomart_annotations_human.tab': No such file or directory
Execution halted
```

**Comment by vplagnol** [comment]
Are you using the version 7 or 8 of the pipeline?
I am trying to rationalize the locations:

/scratch2/vyp-scratch2/reference_datasets/RNASeq/Human_hg38/

On Thu, Nov 26, 2015 at 1:47 PM, Nikolas Pontikos notifications@github.com
wrote:

> Is this file not meant to be stored in the repo?
> 
> > annotations <- read.table(annotation.file, header = TRUE, sep = '\t', quote = "")
> > Error in file(file, "rt") : cannot open the connection
> > Calls: read.table -> file
> > In addition: Warning message:
> > In file(file, "rt") :
> >   cannot open file '/home/rmhanpo/bin/RNASeq_pipeline/bundle/human_hg38/biomart/biomart_annotations_human.tab': No such file or directory
> > Execution halted
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/plagnollab/RNASeq_pipeline/issues/7.

## 

Vincent Plagnol
University College London Genetics Institute
Darwin building, office 210
Gower Street, London, WC1E 6BT
Cell: +44-(0)7946-546923
Office: +44-(0) 2031-084002
Website: http://www.ucl.ac.uk/ugi/research/vincentplagnol
Lab blog: http://plagnol-lab.blogspot.co.uk/

**Comment by pontikos** [comment]
version 8

**Comment by vplagnol** [comment]
So version 8 should find all of these files, I am surprised you still have
links pointing to some other location.
I need to figure out what links are causing the pbm.

On Thu, Nov 26, 2015 at 2:12 PM, Nikolas Pontikos notifications@github.com
wrote:

> version 8
> 
> On 26 November 2015 at 13:53, Vincent Plagnol notifications@github.com
> wrote:
> 
> > Are you using the version 7 or 8 of the pipeline?
> > I am trying to rationalize the locations:
> > 
> > /scratch2/vyp-scratch2/reference_datasets/RNASeq/Human_hg38/
> > 
> > On Thu, Nov 26, 2015 at 1:47 PM, Nikolas Pontikos <
> > notifications@github.com>
> > wrote:
> > 
> > > Is this file not meant to be stored in the repo?
> > > 
> > > > annotations <- read.table(annotation.file, header = TRUE, sep = '\t',
> > > > quote = "")
> > > > Error in file(file, "rt") : cannot open the connection
> > > > Calls: read.table -> file
> > > > In addition: Warning message:
> > > > In file(file, "rt") :
> > > > cannot open file
> > 
> > '/home/rmhanpo/bin/RNASeq_pipeline/bundle/human_hg38/biomart/biomart_annotations_human.tab':
> > No such file or directory
> > 
> > > Execution halted
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/plagnollab/RNASeq_pipeline/issues/7.
> > 
> > ## 
> > 
> > Vincent Plagnol
> > University College London Genetics Institute
> > Darwin building, office 210
> > Gower Street, London, WC1E 6BT
> > Cell: +44-(0)7946-546923
> > Office: +44-(0) 2031-084002
> > Website: http://www.ucl.ac.uk/ugi/research/vincentplagnol
> > Lab blog: http://plagnol-lab.blogspot.co.uk/
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/plagnollab/RNASeq_pipeline/issues/7#issuecomment-159921361
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/plagnollab/RNASeq_pipeline/issues/7#issuecomment-159924796
> .

## 

Vincent Plagnol
University College London Genetics Institute
Darwin building, office 210
Gower Street, London, WC1E 6BT
Cell: +44-(0)7946-546923
Office: +44-(0) 2031-084002
Website: http://www.ucl.ac.uk/ugi/research/vincentplagnol

**Comment by pontikos** [comment]
so the problem i think is the generating script is passing these files on the command line see:

```
/cluster/project8/vyp/pontikos/People/JessicaGardner/output/cluster/submission/starSubmissionStep3.sh
```

```
#!/bin/bash
#$ -S /bin/bash
#$ -o /cluster/project8/vyp/pontikos/People/JessicaGardner/output/cluster/out
#$ -e /cluster/project8/vyp/pontikos/People/JessicaGardner/output/cluster/error
#$ -cwd
#$ -pe smp 4
#$ -l tmem=5.9G,h_vmem=5.9G
#$ -V
#$ -R y
#$ -l h_rt=21:50:00

/cluster/project8/vyp/vincent/Software/R-3.2.2/bin/R CMD BATCH --no-save --no-restore --gff=/scratch2/vyp-scratch2/reference_datasets/RNASeq/Human_hg38/Homo_sapiens.GRCh38.82_fixed.gff --annotation.file=/home/rmhanpo/bin/RNASeq_pipeline/bundle/human_hg38/biomart/biomart_annotations_human.tab --keep.dups=FALSE --support.frame=input-trimmed.txt --code=JessicaGardner_X --iFolder=/cluster/project8/vyp/pontikos/People/JessicaGardner/output /home/rmhanpo/bin/RNASeq_pipeline//counts_prepare_pipeline.R /cluster/project8/vyp/pontikos/People/JessicaGardner/output/cluster/R/count_prepare.out

/cluster/project8/vyp/vincent/Software/R-3.2.2/bin/R CMD BATCH --no-save --no-restore --keep.sex=FALSE --support.frame=input-trimmed.txt --keep.dups=FALSE --code=JessicaGardner_X --annotation.file=/home/rmhanpo/bin/RNASeq_pipeline/bundle/human_hg38/biomart/biomart_annotations_human.tab --iFolder=/cluster/project8/vyp/pontikos/People/JessicaGardner/output /home/rmhanpo/bin/RNASeq_pipeline//deseq2_pipeline.R /cluster/project8/vyp/pontikos/People/JessicaGardner/output/cluster/R/deseq_JessicaGardner_X.out

/cluster/project8/vyp/vincent/Software/R-3.2.2/bin/R CMD BATCH --no-save --no-restore --gff=/scratch2/vyp-scratch2/reference_datasets/RNASeq/Human_hg38/Homo_sapiens.GRCh38.82_fixed.gff --keep.sex=FALSE --keep.dups=FALSE --support.frame=input-trimmed.txt --code=JessicaGardner_X --annotation.file=/home/rmhanpo/bin/RNASeq_pipeline/bundle/human_hg38/biomart/biomart_annotations_human.tab --iFolder=/cluster/project8/vyp/pontikos/People/JessicaGardner/output /home/rmhanpo/bin/RNASeq_pipeline//dexseq_pipeline_v2.R /cluster/project8/vyp/pontikos/People/JessicaGardner/output/cluster/R/dexseq_JessicaGardner_X.out
```

**Comment by pontikos** [comment]
ok so it's obvious, the culprit is this line:
https://github.com/plagnollab/RNASeq_pipeline/blob/master/RNAseq_pipeline_v8.sh#L266

So just hardcode the correct path there?

**Comment by pontikos** [comment]
Fixed it myself.

https://github.com/plagnollab/RNASeq_pipeline/commit/6ab78d67bcf525b17e67fbe51bcac3bda2c758bb
